# Generated by Django 5.2.16 on 2026-08-03 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('general', 'General & Personal'), ('leadership', 'Leadership & Career'), ('technology', 'AI & Technology'), ('social', 'Social & Climate'), ('interview', 'Job Interview Preparation')], default='general', max_length=50)),
                ('difficulty', models.CharField(default='Intermediate', max_length=20)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_icon', models.CharField(default='fa-award', help_text='FontAwesome icon class', max_length=50)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(default='Speech Practice', max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('microphone_device', models.CharField(default='Default Microphone', max_length=255)),
                ('language', models.CharField(default='English (US)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(blank=True, max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speech_audio/')),
                ('transcript', models.TextField(help_text='Transcribed speech text.')),
                ('duration_seconds', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_sessions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('grammar_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('vocabulary_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('fluency_score', models.IntegerField(default=0)),
                ('strengths_json', models.TextField(default='[]', help_text='JSON list of strengths')),
                ('weaknesses_json', models.TextField(default='[]', help_text='JSON list of weaknesses')),
                ('mistakes_json', models.TextField(default='[]', help_text='JSON list of grammar/vocabulary mistakes with corrections')),
                ('suggestions_json', models.TextField(default='[]', help_text='JSON list of actionable improvement suggestions')),
                ('motivational_feedback', models.TextField(blank=True, default='Great effort! Keep practicing to elevate your speaking.')),
                ('exercises_json', models.TextField(default='[]', help_text='JSON list of recommended practice exercises')),
                ('pdf_report', models.CharField(blank=True, help_text='Relative or absolute path to generated PDF in reports/ dir', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='app.speechsession')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Grammar, Vocabulary, Confidence, Fluency, Communication, Overall', max_length=50)),
                ('score_value', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app.speechsession')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0)),
                ('weekly_improvement', models.FloatField(default=0.0, help_text='Percentage improvement over last week')),
                ('monthly_improvement', models.FloatField(default=0.0, help_text='Percentage improvement over last month')),
                ('avg_grammar', models.FloatField(default=0.0)),
                ('avg_vocabulary', models.FloatField(default=0.0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('avg_fluency', models.FloatField(default=0.0)),
                ('avg_communication', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='Passionate about mastering public speaking and communication skills.')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('practice_streak', models.IntegerField(default=1, help_text='Current daily speaking practice streak.')),
                ('total_practice_time', models.IntegerField(default=0, help_text='Total practice duration in seconds.')),
                ('average_score', models.FloatField(default=0.0, help_text='Overall average AI speaking score.')),
                ('highest_score', models.FloatField(default=0.0, help_text='Highest overall AI speaking score.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
