# Generated by Django 5.2.16 on 2026-08-14 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_speechsession_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(default='English', max_length=50)),
                ('daily_practice_minutes', models.IntegerField(default=15)),
                ('practice_days_per_week', models.IntegerField(default=3)),
                ('main_goal', models.CharField(default='Improve general speaking', max_length=100)),
                ('current_level', models.CharField(default='Intermediate', max_length=50)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('error_text', models.TextField(help_text='The mistake the user made')),
                ('correction', models.TextField(help_text='The corrected version')),
                ('frequency', models.IntegerField(default=1)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(default=1)),
                ('day', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=255)),
                ('duration', models.IntegerField(default=10, help_text='Duration in minutes')),
                ('focus_area', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
