# Generated by Django 6.0.1 on 2026-09-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coachingpreference_errorhistory_practiceplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechreport',
            name='tts_audio_path',
            field=models.CharField(blank=True, help_text='Path to generated TTS feedback audio', max_length=500, null=True),
        ),
    ]
