# Generated by Django 6.0.1 on 2026-09-24 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_speechreport_tts_audio_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interview_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('filler_count', models.IntegerField(default=0)),
                ('speaking_rate', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_number', models.IntegerField(default=1)),
                ('question_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.IntegerField(default=0)),
                ('technical_accuracy', models.IntegerField(default=0)),
                ('completeness_score', models.IntegerField(default=0)),
                ('structure_score', models.IntegerField(default=0)),
                ('clarity_score', models.IntegerField(default=0)),
                ('grammar_score', models.IntegerField(default=0)),
                ('feedback_text', models.TextField(blank=True)),
                ('missing_points_json', models.TextField(default='[]')),
                ('suggestions_json', models.TextField(default='[]')),
                ('correct_points_json', models.TextField(default='[]')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.interviewanswer')),
            ],
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.interviewquestion'),
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('interview_language', models.CharField(default='English', max_length=50)),
                ('total_questions', models.IntegerField(default=5)),
                ('completed_questions', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.interviewsession'),
        ),
    ]
