# Generated by Django 5.2.16 on 2026-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_interviewanswer_interviewquestion_interviewfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='classification',
            field=models.CharField(default='Not Evaluated', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='incorrect_points_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='evaluation_criteria_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='expected_points_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='ideal_answer',
            field=models.TextField(blank=True),
        ),
    ]
