# Generated by Django 5.2.16 on 2026-09-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_interviewfeedback_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='answer_status',
            field=models.CharField(default='ANSWERED', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='evaluation_status',
            field=models.CharField(default='EVALUATED', max_length=20),
        ),
    ]
