# Generated by Django 5.2.16 on 2026-09-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_interviewanswer_answer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_contact_pct', models.IntegerField(default=0)),
                ('expression_variety_score', models.IntegerField(default=0)),
                ('posture_score', models.IntegerField(default=0)),
                ('face_detected_pct', models.IntegerField(default=0)),
                ('gesture_activity_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_presence', to='app.interviewanswer')),
                ('speech_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_presence', to='app.speechsession')),
            ],
        ),
    ]
