# Generated by Django 6.0.1 on 2026-09-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_visualpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualpresence',
            name='face_count_violations_json',
            field=models.TextField(default='[]', help_text='JSON list of {timestamp, duration} when >1 face was detected'),
        ),
        migrations.AddField(
            model_name='visualpresence',
            name='gaze_away_events_json',
            field=models.TextField(default='[]', help_text='JSON list of {timestamp, duration} when user looked away'),
        ),
    ]
