# Generated by Django 6.0.1 on 2026-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_visualpresence_face_count_violations_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='model_answer',
            field=models.TextField(blank=True),
        ),
    ]
